modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Direwolf20-MC/ChargingGadgets/issues"

[[mods]]
modId="charginggadgets"
version="${file.jarVersion}"
displayName="Charging Gadgets"
updateJSONURL="https://raw.githubusercontent.com/Direwolf20-MC/ChargingGadgets/master/update.json"
displayURL="https://github.com/Direwolf20-MC/ChargingGadgets"
#logoFile="examplemod.png"
credits="Direwolf20, ErrorMikey, Lex and the entire forge team."
authors="Direwolf20, ErrorMikey"
description='''
    It's a gadget (or a block?) that charges things, what more could you ask for?
'''

[[dependencies.charginggadgets]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"